version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ['*']
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns: ['*']
  - package-ecosystem: npm
    directory: /integrations
    schedule:
      interval: weekly
    groups:
      browser-integration-dependencies:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
