import type { HealthRow, TrafficRow } from "./types";

export const trafficRows: TrafficRow[] = [
  {
    id: "req-1042",
    time: "14:32:08",
    action: "PROXY",
    host: "catalog.example.invalid",
    pool: "Residential CA",
    proxy: "ca-tor-014",
    status: 200,
    upstream: "124.8 KB",
    latency: "612 ms",
  },
  {
    id: "req-1041",
    time: "14:32:06",
    action: "BLOCK",
    host: "metrics.example.invalid",
    pool: "-",
    proxy: "-",
    status: 0,
    upstream: "0 B",
    latency: "1 ms",
  },
  {
    id: "req-1040",
    time: "14:32:04",
    action: "PROXY",
    host: "api.example.invalid",
    pool: "Datacenter US",
    proxy: "us-chi-008",
    status: 200,
    upstream: "8.1 KB",
    latency: "148 ms",
  },
  {
    id: "req-1039",
    time: "14:31:59",
    action: "CACHE",
    host: "assets.example.invalid",
    pool: "-",
    proxy: "-",
    status: 200,
    upstream: "0 B",
    latency: "4 ms",
  },
  {
    id: "req-1038",
    time: "14:31:56",
    action: "PROXY",
    host: "search.example.invalid",
    pool: "Residential CA",
    proxy: "ca-tor-003",
    status: 429,
    upstream: "2.4 KB",
    latency: "2.4 s",
  },
  {
    id: "req-1037",
    time: "14:31:51",
    action: "BLOCK",
    host: "tracker.example.invalid",
    pool: "-",
    proxy: "-",
    status: 0,
    upstream: "0 B",
    latency: "1 ms",
  },
];

export const healthRows: HealthRow[] = [
  {
    name: "ca-tor-014",
    pool: "Residential CA",
    location: "Toronto, CA",
    score: 94,
    latency: "612 ms",
    state: "healthy",
  },
  {
    name: "us-chi-008",
    pool: "Datacenter US",
    location: "Chicago, US",
    score: 89,
    latency: "148 ms",
    state: "healthy",
  },
  {
    name: "ca-tor-003",
    pool: "Residential CA",
    location: "Toronto, CA",
    score: 58,
    latency: "2.4 s",
    state: "degraded",
  },
  {
    name: "us-nyc-002",
    pool: "Datacenter US",
    location: "New York, US",
    score: 18,
    latency: "timeout",
    state: "quarantined",
  },
];

export const trafficSeries = [
  24, 32, 29, 48, 42, 64, 57, 76, 67, 84, 76, 93, 85, 76, 88, 72, 94, 82, 70,
  78, 64, 75, 59, 68,
];
